### ISSUE TITLE
How do you move the menu bar out of the notch area ?

### ISSUE THREAD

**Issue by pkasson** [kyan/kyan_bar#47]
When you run your app on a MacBook with a notch, the menu bar is hidden, is in that notch area - how can you move it as far right as possible next to any other menu bars ?

**Comment by whomwah** [comment]
If you have too many status bar items you are right they go missing! I have this issue too. You can re-arrange status bar items to make sure the ones you like don't ever get hidden.

https://support.apple.com/en-gb/guide/mac-help/mchlp1446/mac#:~:text=Status%20menus&text=You%20can%20choose%20which%20items,out%20of%20the%20menu%20bar.
